/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Usuario
 */
public class FrmTelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form FrmTelaInicial
     */
    public FrmTelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuArquivo = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        JMenuCadastrarCategoria = new javax.swing.JMenuItem();
        JMenuCadastrarProduto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        JMenuRelatorios = new javax.swing.JMenuItem();
        JMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("inicio");

        JMenuArquivo.setText("Gerenciar");
        JMenuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuArquivoActionPerformed(evt);
            }
        });

        jMenu3.setText("Cadastrar");

        JMenuCadastrarCategoria.setText("Cadastrar Categoria");
        JMenuCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuCadastrarCategoria);

        JMenuCadastrarProduto.setText("Cadastrar Produto");
        JMenuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCadastrarProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuCadastrarProduto);

        JMenuArquivo.add(jMenu3);

        jMenu4.setText("Editar");

        jMenuItem2.setText("Editar Categoria");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Editar Produto");
        jMenu4.add(jMenuItem3);

        JMenuArquivo.add(jMenu4);

        jMenuBar1.add(JMenuArquivo);

        jMenu1.setText("Outros");

        jMenu5.setText("Relatórios");

        JMenuRelatorios.setText("Balanço");
        JMenuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuRelatoriosActionPerformed(evt);
            }
        });
        jMenu5.add(JMenuRelatorios);

        jMenu1.add(jMenu5);

        JMenuSair.setText("Sair");
        JMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCadastrarProdutoActionPerformed
        FrmCadastroProduto objeto = new FrmCadastroProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuCadastrarProdutoActionPerformed

    private void JMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuSairActionPerformed

    private void JMenuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuArquivoActionPerformed

    private void JMenuCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCadastrarCategoriaActionPerformed
        FrmCadastroCategoria objeto = new FrmCadastroCategoria();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuCadastrarCategoriaActionPerformed

    private void JMenuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuArquivo;
    private javax.swing.JMenuItem JMenuCadastrarCategoria;
    private javax.swing.JMenuItem JMenuCadastrarProduto;
    private javax.swing.JMenuItem JMenuRelatorios;
    private javax.swing.JMenuItem JMenuSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
